const CRONOGRAMA_DATA = {
  "config": {
    "fecha_inicio": "2026-01-19",
    "cliente": "CENIT",
    "proyecto": "GREENLOG"
  },
  "actividades": [
    {
      "id": "F0",
      "fase": "FASE 0: INICIO Y PLANEACIÓN",
      "actividad": "Inicio y Planeación del Proyecto",
      "tipo": "PRINCIPAL",
      "semana_inicio": 1,
      "duracion": 2,
      "responsable": "Freelancer + CENIT",
      "porcentaje": 0,
      "estado": "Pendiente",
      "color": "#3498db"
    },
    {
      "id": "F0-S1",
      "padre": "F0",
      "actividad": "Kickoff Meeting con CENIT",
      "tipo": "SUB",
      "semana_inicio": 1,
      "duracion": 1,
      "responsable": "Freelancer + PO CENIT",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F0-S2",
      "padre": "F0",
      "actividad": "Matriz RACI y Canales de Comunicación",
      "tipo": "SUB",
      "semana_inicio": 1,
      "duracion": 1,
      "responsable": "Freelancer + CENIT",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F0-S3",
      "padre": "F0",
      "actividad": "Validación de Alcance y Criterios",
      "tipo": "SUB",
      "semana_inicio": 1,
      "duracion": 1,
      "responsable": "PO CENIT",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F0-S4",
      "padre": "F0",
      "actividad": "Accesos TI y Usuario de Desarrollo",
      "tipo": "SUB",
      "semana_inicio": 2,
      "duracion": 1,
      "responsable": "TI CENIT",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F1",
      "fase": "FASE 1: PLANEACIÓN Y MONITOREO",
      "actividad": "Desarrollo Módulo de Planeación",
      "tipo": "PRINCIPAL",
      "semana_inicio": 3,
      "duracion": 4,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente",
      "color": "#2ecc71"
    },
    {
      "id": "F1-S1",
      "padre": "F1",
      "actividad": "Talleres de levantamiento reglas del negocio",
      "tipo": "SUB",
      "semana_inicio": 3,
      "duracion": 1,
      "responsable": "Freelancer + SME",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F1-S2",
      "padre": "F1",
      "actividad": "Diseño Modelo de Datos Estandarizado",
      "tipo": "SUB",
      "semana_inicio": 3,
      "duracion": 2,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F1-S3",
      "padre": "F1",
      "actividad": "Configuración de Catálogos Maestros",
      "tipo": "SUB",
      "semana_inicio": 4,
      "duracion": 1,
      "responsable": "Freelancer + CENIT",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F1-S4",
      "padre": "F1",
      "actividad": "Construcción Pantallas de Planeación",
      "tipo": "SUB",
      "semana_inicio": 4,
      "duracion": 2,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F1-S5",
      "padre": "F1",
      "actividad": "Control de Avance y Desviaciones",
      "tipo": "SUB",
      "semana_inicio": 5,
      "duracion": 2,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F1-S6",
      "padre": "F1",
      "actividad": "UAT y Aceptación Fase 1",
      "tipo": "SUB",
      "semana_inicio": 6,
      "duracion": 1,
      "responsable": "Operación CENIT",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F2",
      "fase": "FASE 2: EJECUCIÓN Y CUMPLIMIENTO",
      "actividad": "Desarrollo Módulo de Ejecución",
      "tipo": "PRINCIPAL",
      "semana_inicio": 7,
      "duracion": 4,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente",
      "color": "#f39c12"
    },
    {
      "id": "F2-S1",
      "padre": "F2",
      "actividad": "Módulo Registro de Ejecución y Novedades",
      "tipo": "SUB",
      "semana_inicio": 7,
      "duracion": 2,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F2-S2",
      "padre": "F2",
      "actividad": "Gestión Portafolio de Evidencias",
      "tipo": "SUB",
      "semana_inicio": 7,
      "duracion": 2,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F2-S3",
      "padre": "F2",
      "actividad": "Checklist de Cumplimiento Ambiental",
      "tipo": "SUB",
      "semana_inicio": 8,
      "duracion": 2,
      "responsable": "Freelancer + SME",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F2-S4",
      "padre": "F2",
      "actividad": "Gestión de Roles y Auditoría de Acciones",
      "tipo": "SUB",
      "semana_inicio": 9,
      "duracion": 2,
      "responsable": "Freelancer + TI",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F2-S5",
      "padre": "F2",
      "actividad": "UAT y Aceptación Fase 2",
      "tipo": "SUB",
      "semana_inicio": 10,
      "duracion": 1,
      "responsable": "Supervisor CENIT",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F3",
      "fase": "FASE 3: DASHBOARD Y ANALÍTICA",
      "actividad": "Desarrollo Dashboard Integral",
      "tipo": "PRINCIPAL",
      "semana_inicio": 11,
      "duracion": 3,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente",
      "color": "#9b59b6"
    },
    {
      "id": "F3-S1",
      "padre": "F3",
      "actividad": "Definición y Construcción de KPIs",
      "tipo": "SUB",
      "semana_inicio": 11,
      "duracion": 2,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F3-S2",
      "padre": "F3",
      "actividad": "Alertas Avanzadas y Tendencias",
      "tipo": "SUB",
      "semana_inicio": 12,
      "duracion": 1,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "F3-S3",
      "padre": "F3",
      "actividad": "Reportes Exportables y UAT Final",
      "tipo": "SUB",
      "semana_inicio": 13,
      "duracion": 1,
      "responsable": "PO Gerencial",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "FL",
      "fase": "PROCESO TRANSVERSAL",
      "actividad": "Implementación Formato Laboratorio PDF",
      "tipo": "PRINCIPAL",
      "semana_inicio": 11,
      "duracion": 3,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente",
      "color": "#1abc9c"
    },
    {
      "id": "FL-S1",
      "padre": "FL",
      "actividad": "Generación Automática de Documento",
      "tipo": "SUB",
      "semana_inicio": 11,
      "duracion": 2,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "FL-S2",
      "padre": "FL",
      "actividad": "Flujo de Firma Electrónica / Aprobación",
      "tipo": "SUB",
      "semana_inicio": 12,
      "duracion": 2,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "DOC",
      "fase": "DOCUMENTACIÓN Y CAPACITACIÓN",
      "actividad": "Manuales y Guías Técnicas",
      "tipo": "PRINCIPAL",
      "semana_inicio": 14,
      "duracion": 4,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente",
      "color": "#e74c3c"
    },
    {
      "id": "DOC-S1",
      "padre": "DOC",
      "actividad": "Manual de Usuario y Operativo",
      "tipo": "SUB",
      "semana_inicio": 14,
      "duracion": 2,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "DOC-S2",
      "padre": "DOC",
      "actividad": "Manual de Administración y TI",
      "tipo": "SUB",
      "semana_inicio": 15,
      "duracion": 2,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "CAP",
      "fase": "DOCUMENTACIÓN Y CAPACITACIÓN",
      "actividad": "Plan de Capacitación y Cierre",
      "tipo": "PRINCIPAL",
      "semana_inicio": 18,
      "duracion": 3,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente",
      "color": "#d35400"
    },
    {
      "id": "CAP-S1",
      "padre": "CAP",
      "actividad": "Sesiones Capacitación Usuarios Operativos",
      "tipo": "SUB",
      "semana_inicio": 18,
      "duracion": 1,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "CAP-S2",
      "padre": "CAP",
      "actividad": "Sesiones Supervisores y Administradores",
      "tipo": "SUB",
      "semana_inicio": 19,
      "duracion": 1,
      "responsable": "Freelancer",
      "porcentaje": 0,
      "estado": "Pendiente"
    },
    {
      "id": "CAP-S3",
      "padre": "CAP",
      "actividad": "Despliegue Producción y Acta Final",
      "tipo": "SUB",
      "semana_inicio": 20,
      "duracion": 1,
      "responsable": "Freelancer + PO CENIT",
      "porcentaje": 0,
      "estado": "Pendiente"
    }
  ]
};